version: '3.9'

services:
   app:
      build: .
      container_name: app
      command: sh -c "tail -f /dev/null"
      volumes:
         - .:/usr/app
         - ./node_modules:/usr/app/node_modules
      ports:
         - "8080:5173"